### ISSUE TITLE
Please help how to solve this , Thanks

### ISSUE THREAD

**Issue by Tigercat000** [TheAirBlow/HyperFuck#1]
PS C:\HyperFuck-main> # connect your Android device before continuing
PS C:\HyperFuck-main> # make sure to enable USB debugging
PS C:\HyperFuck-main> python main.py
PS C:\HyperFuck-main> adb push Settings.apk /data/local/tmp/Settings.apk
adb server is out of date.  killing...
* daemon started successfully *
0 KB/s (134 bytes in 1.000s)
PS C:\HyperFuck-main> adb shell pm install -r -d /data/local/tmp/Settings.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/Settings.apk: Failed to parse /data/local/tmp/Settings.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:717)
        at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1577)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1543)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:236)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6551)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4352)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6535)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)
Caused by: java.io.IOException: Failed to load asset path /data/local/tmp/Settings.apk from fd 662
        at android.content.res.ApkAssets.nativeLoadFd(Native Method)
        at android.content.res.ApkAssets.<init>(ApkAssets.java:309)
        at android.content.res.ApkAssets.loadFromFd(ApkAssets.java:180)
        at android.content.pm.parsing.ApkLiteParseUtils.parseApkLiteInner(ApkLiteParseUtils.java:356)
        at android.content.pm.parsing.ApkLiteParseUtils.parseApkLite(ApkLiteParseUtils.java:344)
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:711)
        ... 12 more

**Comment by TheAirBlow** [comment]
Replied elsewhere alreadh

**Comment by Tigercat000** [comment]
> Replied elsewhere already

Thanks
